import os
import glob
import re
from datetime import datetime

def parse_markdown_title(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read(1000)
    match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
    if match:
        return match.group(1).strip()
    return os.path.basename(filepath)

def build_index(base_path):
    index_path = os.path.join(base_path, "INDEX.md")
    
    issues_closed_dir = os.path.join(base_path, "issues", "closed")
    issues_open_dir = os.path.join(base_path, "issues", "open")
    decisions_dir = os.path.join(base_path, "decisions")
    kb_dir = os.path.join(base_path, "knowledge_base")
    
    out = []
    out.append("# AI-Chat Master Index\n")
    out.append("This file is auto-generated by `utils/build_index.py`. Do not edit manually.\n")
    
    out.append("## Decisions (ADRs)\n")
    out.append("| File | Title |\n|---|---|\n")
    adrs = sorted(glob.glob(os.path.join(decisions_dir, "*.md")), reverse=True)
    for adr in adrs:
        title = parse_markdown_title(adr)
        # Using forward slashes for markdown links
        rel_path = os.path.relpath(adr, base_path).replace("\\", "/")
        out.append(f"| [{os.path.basename(adr)}]({rel_path}) | {title} |\n")
        
    out.append("\n## Open Issues\n")
    out.append("| File | Title |\n|---|---|\n")
    opens = sorted(glob.glob(os.path.join(issues_open_dir, "*.md")))
    for issue in opens:
        title = parse_markdown_title(issue)
        rel_path = os.path.relpath(issue, base_path).replace("\\", "/")
        out.append(f"| [{os.path.basename(issue)}]({rel_path}) | {title} |\n")
        
    out.append("\n## Closed Issues (Changelog)\n")
    out.append("| File | Title |\n|---|---|\n")
    closed = sorted(glob.glob(os.path.join(issues_closed_dir, "*.md")), reverse=True)
    for issue in closed:
        title = parse_markdown_title(issue)
        rel_path = os.path.relpath(issue, base_path).replace("\\", "/")
        out.append(f"| [{os.path.basename(issue)}]({rel_path}) | {title} |\n")
        
    out.append("\n## Knowledge Base\n")
    out.append("| File | Title |\n|---|---|\n")
    kbs = sorted(glob.glob(os.path.join(kb_dir, "*.md")))
    for kb in kbs:
        title = parse_markdown_title(kb)
        rel_path = os.path.relpath(kb, base_path).replace("\\", "/")
        out.append(f"| [{os.path.basename(kb)}]({rel_path}) | {title} |\n")
        
    with open(index_path, "w", encoding="utf-8") as f:
        f.writelines(out)
        
    print(f"Index successfully built at {index_path}")

if __name__ == "__main__":
    import sys
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    build_index(base)
